name: Build the okd image for arm64

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  setup-tools:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Set up Podman, OpenShift CLI, and Skopeo
      run: |
        echo "Installing Podman"
        sudo apt-get update
        sudo apt-get install -y podman

        echo "Installing OpenShift CLI"
        curl -LO "https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/stable/openshift-client-linux.tar.gz"
        tar -xvf openshift-client-linux.tar.gz
        sudo mv oc /usr/local/bin/
        sudo mv kubectl /usr/local/bin/
        rm -f openshift-client-linux.tar.gz

        echo "Installing Skopeo"
        sudo apt-get install -y skopeo

    - name: Remove unwanted stuff to free up disk image
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          sudo docker image prune --all --force

          sudo swapoff -a
          sudo rm -f /mnt/swapfile

          APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
          $APT_PARAMS remove -y '^dotnet-.*'
          $APT_PARAMS remove -y '^llvm-.*'
          $APT_PARAMS remove -y '^php.*'
          $APT_PARAMS remove -y '^mongodb-.*'
          $APT_PARAMS remove -y '^mysql-.*'
          $APT_PARAMS remove -y azure-cli google-* firefox powershell mono-devel libgl1-mesa-dri
          $APT_PARAMS autoremove --purge -y
          $APT_PARAMS autoclean
          $APT_PARAMS clean

    - name: Verify installations
      run: |
        echo "Verifying Podman"
        podman --version

        echo "Verifying OpenShift CLI"
        oc version --client

        echo "Verifying Skopeo"
        skopeo --version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}
    - name: run build-image script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        pushd okd-arm64
        chmod +x build-images.sh
        ./build-images.sh
        popd
    - name: build microshift image and push
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 45
        max_attempts: 3
        command: ./create-microshift-image.sh
    - name: Setup tmate session
      if: ${{ failure() && steps.image.conclusion == 'failure' }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
      with:
        limit-access-to-actor: true
